# ШерстовАИ_КМБО-03-23_ПР_2

# 1.3.1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np
a = [(i % 2 + i // 8) % 2 for i in range(64)]
a = np.array(a).reshape(8, 8)
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию ```arange```.

In [2]:
import numpy as np
a = np.arange(4)
a = np.tile(a, (5, 1))
print(a)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


# 1.3.3
Создать массив 3x3x3 со случайными значениями.

In [3]:
import numpy as np
a = np.random.randint(10, size=27).reshape(3, 3, 3)
print(a)

[[[1 3 6]
  [7 0 9]
  [3 5 4]]

 [[6 0 9]
  [7 8 9]
  [0 0 8]]

 [[5 3 3]
  [7 3 3]
  [1 1 4]]]


# 1.3.4
Создать матрицу с 0 внутри, и 1 на границах.

In [4]:
import numpy as np
a = np.array([0 for i in range(25)]).reshape(5, 5)
for i in range(len(a)):
  for j in range(len(a[0])):
    if i == 0 or i == len(a) - 1 or j == 0 or j == len(a[0]) - 1:
      a[i][j] = 1
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 1.3.5
Создайте массив и отсортируйте его по убыванию.

In [5]:
import numpy as np
a = np.random.randint(10, size=15)
print(a)
a = np.sort(a)[::-1]
print(a)

[0 3 1 7 9 5 0 0 3 2 4 7 3 6 7]
[9 7 7 7 6 5 4 3 3 3 2 1 0 0 0]


# 1.3.6
Создайте матрицу, выведите ее форму, размер и размерность.

In [6]:
import numpy as np
a = np.random.randint(10, size=30).reshape(5, 6)
print(a, '\n')
print("Форма:", a.shape)
print("Размер:", a.size)
print("Размерность:", a.ndim)

[[9 1 2 2 2 8]
 [2 7 5 3 5 0]
 [6 7 2 8 2 3]
 [7 5 4 1 3 1]
 [8 8 7 6 6 1]] 

Форма: (5, 6)
Размер: 30
Размерность: 2


# 2.3.1
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [8]:
import pandas as pd
a = pd.Series(map(float, input("Координаты первой точки: ").split()))
b = pd.Series(map(float, input("Координаты второй точки: ").split()))
distance = 0
for i in range(len(a)):
  distance += (a[i] - b[i]) ** 2
distance **= 0.5
print(distance)

Координаты первой точки: 0 3
Координаты второй точки: 4 0
5.0


# 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [9]:
import pandas as pd
url = "https://raw.githubusercontent.com/AvalonAVL/ai-prac-1/main/AAPL.csv"
dataframe = pd.read_csv(url)
print(dataframe)

           Date        Open        High         Low       Close   Adj Close  \
0    2021-01-04  133.520004  133.610001  126.760002  129.410004  127.331696   
1    2021-01-05  128.889999  131.740005  128.429993  131.009995  128.905991   
2    2021-01-06  127.720001  131.050003  126.379997  126.599998  124.566826   
3    2021-01-07  128.360001  131.630005  127.860001  130.919998  128.817444   
4    2021-01-08  132.429993  132.630005  130.229996  132.050003  129.929291   
..          ...         ...         ...         ...         ...         ...   
246  2021-12-23  175.850006  176.850006  175.270004  176.279999  174.518250   
247  2021-12-27  177.089996  180.419998  177.070007  180.330002  178.527786   
248  2021-12-28  180.160004  181.330002  178.529999  179.289993  177.498138   
249  2021-12-29  179.330002  180.630005  178.139999  179.380005  177.587250   
250  2021-12-30  179.470001  180.570007  178.089996  178.199997  176.419052   

        Volume  
0    143301900  
1     97664900  


# 2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7:
Пронализировать характеристики фрейма данных. <br>
Выберите индивидуальные данные или срезы фрейма данных. <br>
Требуется отобрать строки фрейма данных на основе некоторого
условия. <br> Необходимо сформировать новый фрейм данных.

In [10]:
import pandas as pd
url = "https://raw.githubusercontent.com/AvalonAVL/ai-prac-1/main/AAPL.csv"
dataframe = pd.read_csv(url)
print(dataframe.head(2), end='\n\n')
print(dataframe.tail(2), end='\n\n')
print(dataframe.shape, end='\n\n')
print(dataframe.describe(), end='\n\n')
print(dataframe.iloc[1:4], end='\n\n')
print(dataframe[dataframe["Volume"] >= 10 ** 8].head(2))

         Date        Open        High         Low       Close   Adj Close  \
0  2021-01-04  133.520004  133.610001  126.760002  129.410004  127.331696   
1  2021-01-05  128.889999  131.740005  128.429993  131.009995  128.905991   

      Volume  
0  143301900  
1   97664900  

           Date        Open        High         Low       Close   Adj Close  \
249  2021-12-29  179.330002  180.630005  178.139999  179.380005  177.587250   
250  2021-12-30  179.470001  180.570007  178.089996  178.199997  176.419052   

       Volume  
249  62348900  
250  59773000  

(251, 7)

             Open        High         Low       Close   Adj Close  \
count  251.000000  251.000000  251.000000  251.000000  251.000000   
mean   140.713546  142.200877  139.323545  140.843626  139.061157   
std     14.329380   14.599083   14.275668   14.504792   14.538501   
min    119.029999  120.400002  116.209999  116.360001  114.662354   
25%    128.769997  130.419998  127.099998  128.945000  126.874149   
50%    140.

# 3.3.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(```sepal_length_cm```) с использованием минимаксного преобразования, а
второго (```sepal_width_cm```) с задействованием z-масштабирования.

In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)
minmax_scale = MinMaxScaler(feature_range = (0, 1))
dataframe['sepal_length_cm'] = minmax_scale.fit_transform(np.array(
    dataframe['sepal_length_cm']).reshape(-1, 1))
z_scale = StandardScaler()
dataframe['sepal_width_cm'] = z_scale.fit_transform(np.array(
    dataframe['sepal_width_cm']).reshape(-1, 1))
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]